# Generated by Django 3.2.2 on 2021-05-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('private_key', models.CharField(max_length=128)),
                ('public_key', models.CharField(max_length=128)),
            ],
        ),
    ]
