# Generated by Django 3.2.2 on 2021-05-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('walletapp', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('private_key', models.CharField(max_length=128)),
                ('public_key', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
