# Generated by Django 3.2.2 on 2021-05-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0005_auto_20210509_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=3),
        ),
    ]
