# Generated by Django 3.2.2 on 2021-05-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0006_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
