# Generated by Django 3.2.2 on 2021-05-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0011_auto_20210509_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='output',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.TextField(max_length=128),
        ),
    ]
